-- Migration: Backfill qr_code for dining tables created before qr_code was
-- auto-generated by createTable (they ended up with NULL => unscannable QR).
-- Follows the seed convention: T01 -> table-t01.

-- 1) Fill NULLs with the readable code when it is still free.
UPDATE dining_tables t
SET qr_code = 'table-' || lower(regexp_replace(t.table_number, '[^a-zA-Z0-9]+', '-', 'g'))
WHERE t.qr_code IS NULL
  AND NOT EXISTS (
    SELECT 1
    FROM dining_tables x
    WHERE x.qr_code = 'table-' || lower(regexp_replace(t.table_number, '[^a-zA-Z0-9]+', '-', 'g'))
  );

-- 2) Any leftovers (readable code already taken) get a UUID-based code.
UPDATE dining_tables
SET qr_code = 'table-' || gen_random_uuid()::text
WHERE qr_code IS NULL;
