/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SiteIndexRouteImport } from './routes/site/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SiteTermsRouteImport } from './routes/site/terms'
import { Route as SiteReservationRouteImport } from './routes/site/reservation'
import { Route as SitePrivacyRouteImport } from './routes/site/privacy'
import { Route as SiteMenuRouteImport } from './routes/site/menu'
import { Route as SiteContactRouteImport } from './routes/site/contact'
import { Route as SiteAboutRouteImport } from './routes/site/about'
import { Route as OrderTableCodeRouteImport } from './routes/order.$tableCode'
import { Route as OrderStatusOrderIdRouteImport } from './routes/order-status.$orderId'
import { Route as CustomerSurveyRouteImport } from './routes/customer/survey'
import { Route as AdminTablesRouteImport } from './routes/admin/tables'
import { Route as AdminStaffRouteImport } from './routes/admin/staff'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminServerRouteImport } from './routes/admin/server'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRecipesRouteImport } from './routes/admin/recipes'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminMenuConfigRouteImport } from './routes/admin/menu-config'
import { Route as AdminMenuRouteImport } from './routes/admin/menu'
import { Route as AdminLogisticsRouteImport } from './routes/admin/logistics'
import { Route as AdminLinksRouteImport } from './routes/admin/links'
import { Route as AdminKitchenRouteImport } from './routes/admin/kitchen'
import { Route as AdminIngredientsRouteImport } from './routes/admin/ingredients'
import { Route as AdminFranchiseContentRouteImport } from './routes/admin/franchise-content'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCounterRouteImport } from './routes/admin/counter'
import { Route as AdminContactsRouteImport } from './routes/admin/contacts'
import { Route as SiteFranchiseIndexRouteImport } from './routes/site/franchise/index'
import { Route as SiteFranchiseMenuRouteImport } from './routes/site/franchise/menu'
import { Route as SiteFranchiseInvestmentRouteImport } from './routes/site/franchise/investment'
import { Route as SiteFranchiseAtmosphereRouteImport } from './routes/site/franchise/atmosphere'
import { Route as SiteFranchiseApplyRouteImport } from './routes/site/franchise/apply'

const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/site/',
  path: '/site/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SiteTermsRoute = SiteTermsRouteImport.update({
  id: '/site/terms',
  path: '/site/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteReservationRoute = SiteReservationRouteImport.update({
  id: '/site/reservation',
  path: '/site/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const SitePrivacyRoute = SitePrivacyRouteImport.update({
  id: '/site/privacy',
  path: '/site/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteMenuRoute = SiteMenuRouteImport.update({
  id: '/site/menu',
  path: '/site/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/site/contact',
  path: '/site/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/site/about',
  path: '/site/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderTableCodeRoute = OrderTableCodeRouteImport.update({
  id: '/order/$tableCode',
  path: '/order/$tableCode',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderStatusOrderIdRoute = OrderStatusOrderIdRouteImport.update({
  id: '/order-status/$orderId',
  path: '/order-status/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerSurveyRoute = CustomerSurveyRouteImport.update({
  id: '/customer/survey',
  path: '/customer/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTablesRoute = AdminTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStaffRoute = AdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServerRoute = AdminServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecipesRoute = AdminRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuConfigRoute = AdminMenuConfigRouteImport.update({
  id: '/menu-config',
  path: '/menu-config',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogisticsRoute = AdminLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIngredientsRoute = AdminIngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFranchiseContentRoute = AdminFranchiseContentRouteImport.update({
  id: '/franchise-content',
  path: '/franchise-content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCounterRoute = AdminCounterRouteImport.update({
  id: '/counter',
  path: '/counter',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContactsRoute = AdminContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AdminRoute,
} as any)
const SiteFranchiseIndexRoute = SiteFranchiseIndexRouteImport.update({
  id: '/site/franchise/',
  path: '/site/franchise/',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteFranchiseMenuRoute = SiteFranchiseMenuRouteImport.update({
  id: '/site/franchise/menu',
  path: '/site/franchise/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteFranchiseInvestmentRoute = SiteFranchiseInvestmentRouteImport.update({
  id: '/site/franchise/investment',
  path: '/site/franchise/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteFranchiseAtmosphereRoute = SiteFranchiseAtmosphereRouteImport.update({
  id: '/site/franchise/atmosphere',
  path: '/site/franchise/atmosphere',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteFranchiseApplyRoute = SiteFranchiseApplyRouteImport.update({
  id: '/site/franchise/apply',
  path: '/site/franchise/apply',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/kitchen': typeof KitchenRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/reservation': typeof ReservationRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/counter': typeof AdminCounterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/franchise-content': typeof AdminFranchiseContentRoute
  '/admin/ingredients': typeof AdminIngredientsRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/menu-config': typeof AdminMenuConfigRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/server': typeof AdminServerRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tables': typeof AdminTablesRoute
  '/customer/survey': typeof CustomerSurveyRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/order/$tableCode': typeof OrderTableCodeRoute
  '/site/about': typeof SiteAboutRoute
  '/site/contact': typeof SiteContactRoute
  '/site/menu': typeof SiteMenuRoute
  '/site/privacy': typeof SitePrivacyRoute
  '/site/reservation': typeof SiteReservationRoute
  '/site/terms': typeof SiteTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/site': typeof SiteIndexRoute
  '/site/franchise/apply': typeof SiteFranchiseApplyRoute
  '/site/franchise/atmosphere': typeof SiteFranchiseAtmosphereRoute
  '/site/franchise/investment': typeof SiteFranchiseInvestmentRoute
  '/site/franchise/menu': typeof SiteFranchiseMenuRoute
  '/site/franchise': typeof SiteFranchiseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/kitchen': typeof KitchenRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/reservation': typeof ReservationRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/counter': typeof AdminCounterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/franchise-content': typeof AdminFranchiseContentRoute
  '/admin/ingredients': typeof AdminIngredientsRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/menu-config': typeof AdminMenuConfigRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/server': typeof AdminServerRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tables': typeof AdminTablesRoute
  '/customer/survey': typeof CustomerSurveyRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/order/$tableCode': typeof OrderTableCodeRoute
  '/site/about': typeof SiteAboutRoute
  '/site/contact': typeof SiteContactRoute
  '/site/menu': typeof SiteMenuRoute
  '/site/privacy': typeof SitePrivacyRoute
  '/site/reservation': typeof SiteReservationRoute
  '/site/terms': typeof SiteTermsRoute
  '/admin': typeof AdminIndexRoute
  '/site': typeof SiteIndexRoute
  '/site/franchise/apply': typeof SiteFranchiseApplyRoute
  '/site/franchise/atmosphere': typeof SiteFranchiseAtmosphereRoute
  '/site/franchise/investment': typeof SiteFranchiseInvestmentRoute
  '/site/franchise/menu': typeof SiteFranchiseMenuRoute
  '/site/franchise': typeof SiteFranchiseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/kitchen': typeof KitchenRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/reservation': typeof ReservationRoute
  '/admin/contacts': typeof AdminContactsRoute
  '/admin/counter': typeof AdminCounterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/franchise-content': typeof AdminFranchiseContentRoute
  '/admin/ingredients': typeof AdminIngredientsRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/logistics': typeof AdminLogisticsRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/menu-config': typeof AdminMenuConfigRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/recipes': typeof AdminRecipesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/server': typeof AdminServerRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/staff': typeof AdminStaffRoute
  '/admin/tables': typeof AdminTablesRoute
  '/customer/survey': typeof CustomerSurveyRoute
  '/order-status/$orderId': typeof OrderStatusOrderIdRoute
  '/order/$tableCode': typeof OrderTableCodeRoute
  '/site/about': typeof SiteAboutRoute
  '/site/contact': typeof SiteContactRoute
  '/site/menu': typeof SiteMenuRoute
  '/site/privacy': typeof SitePrivacyRoute
  '/site/reservation': typeof SiteReservationRoute
  '/site/terms': typeof SiteTermsRoute
  '/admin/': typeof AdminIndexRoute
  '/site/': typeof SiteIndexRoute
  '/site/franchise/apply': typeof SiteFranchiseApplyRoute
  '/site/franchise/atmosphere': typeof SiteFranchiseAtmosphereRoute
  '/site/franchise/investment': typeof SiteFranchiseInvestmentRoute
  '/site/franchise/menu': typeof SiteFranchiseMenuRoute
  '/site/franchise/': typeof SiteFranchiseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/kitchen'
    | '/links'
    | '/login'
    | '/menu'
    | '/reservation'
    | '/admin/contacts'
    | '/admin/counter'
    | '/admin/dashboard'
    | '/admin/franchise-content'
    | '/admin/ingredients'
    | '/admin/kitchen'
    | '/admin/links'
    | '/admin/logistics'
    | '/admin/menu'
    | '/admin/menu-config'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/recipes'
    | '/admin/reports'
    | '/admin/server'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/customer/survey'
    | '/order-status/$orderId'
    | '/order/$tableCode'
    | '/site/about'
    | '/site/contact'
    | '/site/menu'
    | '/site/privacy'
    | '/site/reservation'
    | '/site/terms'
    | '/admin/'
    | '/site'
    | '/site/franchise/apply'
    | '/site/franchise/atmosphere'
    | '/site/franchise/investment'
    | '/site/franchise/menu'
    | '/site/franchise'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/kitchen'
    | '/links'
    | '/login'
    | '/menu'
    | '/reservation'
    | '/admin/contacts'
    | '/admin/counter'
    | '/admin/dashboard'
    | '/admin/franchise-content'
    | '/admin/ingredients'
    | '/admin/kitchen'
    | '/admin/links'
    | '/admin/logistics'
    | '/admin/menu'
    | '/admin/menu-config'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/recipes'
    | '/admin/reports'
    | '/admin/server'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/customer/survey'
    | '/order-status/$orderId'
    | '/order/$tableCode'
    | '/site/about'
    | '/site/contact'
    | '/site/menu'
    | '/site/privacy'
    | '/site/reservation'
    | '/site/terms'
    | '/admin'
    | '/site'
    | '/site/franchise/apply'
    | '/site/franchise/atmosphere'
    | '/site/franchise/investment'
    | '/site/franchise/menu'
    | '/site/franchise'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/kitchen'
    | '/links'
    | '/login'
    | '/menu'
    | '/reservation'
    | '/admin/contacts'
    | '/admin/counter'
    | '/admin/dashboard'
    | '/admin/franchise-content'
    | '/admin/ingredients'
    | '/admin/kitchen'
    | '/admin/links'
    | '/admin/logistics'
    | '/admin/menu'
    | '/admin/menu-config'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/recipes'
    | '/admin/reports'
    | '/admin/server'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/tables'
    | '/customer/survey'
    | '/order-status/$orderId'
    | '/order/$tableCode'
    | '/site/about'
    | '/site/contact'
    | '/site/menu'
    | '/site/privacy'
    | '/site/reservation'
    | '/site/terms'
    | '/admin/'
    | '/site/'
    | '/site/franchise/apply'
    | '/site/franchise/atmosphere'
    | '/site/franchise/investment'
    | '/site/franchise/menu'
    | '/site/franchise/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  KitchenRoute: typeof KitchenRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  ReservationRoute: typeof ReservationRoute
  CustomerSurveyRoute: typeof CustomerSurveyRoute
  OrderStatusOrderIdRoute: typeof OrderStatusOrderIdRoute
  OrderTableCodeRoute: typeof OrderTableCodeRoute
  SiteAboutRoute: typeof SiteAboutRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteMenuRoute: typeof SiteMenuRoute
  SitePrivacyRoute: typeof SitePrivacyRoute
  SiteReservationRoute: typeof SiteReservationRoute
  SiteTermsRoute: typeof SiteTermsRoute
  SiteIndexRoute: typeof SiteIndexRoute
  SiteFranchiseApplyRoute: typeof SiteFranchiseApplyRoute
  SiteFranchiseAtmosphereRoute: typeof SiteFranchiseAtmosphereRoute
  SiteFranchiseInvestmentRoute: typeof SiteFranchiseInvestmentRoute
  SiteFranchiseMenuRoute: typeof SiteFranchiseMenuRoute
  SiteFranchiseIndexRoute: typeof SiteFranchiseIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/': {
      id: '/site/'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/site/terms': {
      id: '/site/terms'
      path: '/site/terms'
      fullPath: '/site/terms'
      preLoaderRoute: typeof SiteTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/reservation': {
      id: '/site/reservation'
      path: '/site/reservation'
      fullPath: '/site/reservation'
      preLoaderRoute: typeof SiteReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/privacy': {
      id: '/site/privacy'
      path: '/site/privacy'
      fullPath: '/site/privacy'
      preLoaderRoute: typeof SitePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/menu': {
      id: '/site/menu'
      path: '/site/menu'
      fullPath: '/site/menu'
      preLoaderRoute: typeof SiteMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/contact': {
      id: '/site/contact'
      path: '/site/contact'
      fullPath: '/site/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/about': {
      id: '/site/about'
      path: '/site/about'
      fullPath: '/site/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$tableCode': {
      id: '/order/$tableCode'
      path: '/order/$tableCode'
      fullPath: '/order/$tableCode'
      preLoaderRoute: typeof OrderTableCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-status/$orderId': {
      id: '/order-status/$orderId'
      path: '/order-status/$orderId'
      fullPath: '/order-status/$orderId'
      preLoaderRoute: typeof OrderStatusOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/survey': {
      id: '/customer/survey'
      path: '/customer/survey'
      fullPath: '/customer/survey'
      preLoaderRoute: typeof CustomerSurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/tables': {
      id: '/admin/tables'
      path: '/tables'
      fullPath: '/admin/tables'
      preLoaderRoute: typeof AdminTablesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/staff': {
      id: '/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AdminStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/server': {
      id: '/admin/server'
      path: '/server'
      fullPath: '/admin/server'
      preLoaderRoute: typeof AdminServerRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recipes': {
      id: '/admin/recipes'
      path: '/recipes'
      fullPath: '/admin/recipes'
      preLoaderRoute: typeof AdminRecipesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu-config': {
      id: '/admin/menu-config'
      path: '/menu-config'
      fullPath: '/admin/menu-config'
      preLoaderRoute: typeof AdminMenuConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logistics': {
      id: '/admin/logistics'
      path: '/logistics'
      fullPath: '/admin/logistics'
      preLoaderRoute: typeof AdminLogisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ingredients': {
      id: '/admin/ingredients'
      path: '/ingredients'
      fullPath: '/admin/ingredients'
      preLoaderRoute: typeof AdminIngredientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/franchise-content': {
      id: '/admin/franchise-content'
      path: '/franchise-content'
      fullPath: '/admin/franchise-content'
      preLoaderRoute: typeof AdminFranchiseContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/counter': {
      id: '/admin/counter'
      path: '/counter'
      fullPath: '/admin/counter'
      preLoaderRoute: typeof AdminCounterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contacts': {
      id: '/admin/contacts'
      path: '/contacts'
      fullPath: '/admin/contacts'
      preLoaderRoute: typeof AdminContactsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/site/franchise/': {
      id: '/site/franchise/'
      path: '/site/franchise'
      fullPath: '/site/franchise'
      preLoaderRoute: typeof SiteFranchiseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/franchise/menu': {
      id: '/site/franchise/menu'
      path: '/site/franchise/menu'
      fullPath: '/site/franchise/menu'
      preLoaderRoute: typeof SiteFranchiseMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/franchise/investment': {
      id: '/site/franchise/investment'
      path: '/site/franchise/investment'
      fullPath: '/site/franchise/investment'
      preLoaderRoute: typeof SiteFranchiseInvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/franchise/atmosphere': {
      id: '/site/franchise/atmosphere'
      path: '/site/franchise/atmosphere'
      fullPath: '/site/franchise/atmosphere'
      preLoaderRoute: typeof SiteFranchiseAtmosphereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/site/franchise/apply': {
      id: '/site/franchise/apply'
      path: '/site/franchise/apply'
      fullPath: '/site/franchise/apply'
      preLoaderRoute: typeof SiteFranchiseApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminContactsRoute: typeof AdminContactsRoute
  AdminCounterRoute: typeof AdminCounterRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFranchiseContentRoute: typeof AdminFranchiseContentRoute
  AdminIngredientsRoute: typeof AdminIngredientsRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminLogisticsRoute: typeof AdminLogisticsRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminMenuConfigRoute: typeof AdminMenuConfigRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminRecipesRoute: typeof AdminRecipesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminServerRoute: typeof AdminServerRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStaffRoute: typeof AdminStaffRoute
  AdminTablesRoute: typeof AdminTablesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminContactsRoute: AdminContactsRoute,
  AdminCounterRoute: AdminCounterRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFranchiseContentRoute: AdminFranchiseContentRoute,
  AdminIngredientsRoute: AdminIngredientsRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminLogisticsRoute: AdminLogisticsRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminMenuConfigRoute: AdminMenuConfigRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminRecipesRoute: AdminRecipesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminServerRoute: AdminServerRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStaffRoute: AdminStaffRoute,
  AdminTablesRoute: AdminTablesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  KitchenRoute: KitchenRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  ReservationRoute: ReservationRoute,
  CustomerSurveyRoute: CustomerSurveyRoute,
  OrderStatusOrderIdRoute: OrderStatusOrderIdRoute,
  OrderTableCodeRoute: OrderTableCodeRoute,
  SiteAboutRoute: SiteAboutRoute,
  SiteContactRoute: SiteContactRoute,
  SiteMenuRoute: SiteMenuRoute,
  SitePrivacyRoute: SitePrivacyRoute,
  SiteReservationRoute: SiteReservationRoute,
  SiteTermsRoute: SiteTermsRoute,
  SiteIndexRoute: SiteIndexRoute,
  SiteFranchiseApplyRoute: SiteFranchiseApplyRoute,
  SiteFranchiseAtmosphereRoute: SiteFranchiseAtmosphereRoute,
  SiteFranchiseInvestmentRoute: SiteFranchiseInvestmentRoute,
  SiteFranchiseMenuRoute: SiteFranchiseMenuRoute,
  SiteFranchiseIndexRoute: SiteFranchiseIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
